In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV

In [3]:
df = pd.read_csv("hitters.csv")

df = df.dropna()

dms = pd.get_dummies(df[["League","Division","NewLeague"]])

y = df["Salary"]

x_ = df.drop(["Salary","League","Division","NewLeague"],axis = 1).astype("float64")

x = pd.concat([x_, dms[["League_N","Division_W","NewLeague_N"]]],axis = 1)

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size =0.25, random_state=42)

In [4]:
enet_model = ElasticNet().fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


In [5]:
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [6]:
enet_model.intercept_

-6.465955602112558

In [8]:
# tahmin
enet_model.predict(x_train)[:10]

array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566, 997.76095723,  99.78828622, 311.33763086,
       418.50335021, 879.9502608 ])

In [9]:
y_pred = enet_model.predict(x_test)

In [10]:
np.sqrt(mean_squared_error(y_test,y_pred))

357.1676548181244

In [11]:
r2_score(y_test,y_pred)

0.41070222469326934

# Model Tuning

In [20]:
alphas = 10**np.linspace(10,-2,100)*0.5
enet_cv_model = ElasticNetCV(alphas = alphas,cv =10).fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:617: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3249.9483075737953, tolerance: 3241.424449064271
  model = cd_fast.enet_coordinate_descent_gram(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:617: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4337.003153102472, tolerance: 3241.424449064271
  model = cd_fast.enet_coordinate_descent_gram(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:617: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 5751.4247966222465, tolerance: 3241.424449064271
  model = cd_fast.enet_coordi

In [21]:
enet_cv_model.alpha_

5748.784976988678

In [22]:
enet_cv_model.intercept_

-31.463121225640975

In [23]:
enet_cv_model.coef_

array([ 0.61111381,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.11212622,  0.        ,
        0.25252702,  0.18656722,  0.00444355,  0.30988823,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

In [24]:
#final modeli
enet_tuned = ElasticNet(alpha = enet_cv_model.alpha_).fit(x_train,y_train)

In [25]:
y_pred = enet_tuned.predict(x_test)

In [26]:
np.sqrt(mean_squared_error(y_test,y_pred))

393.9753065850553